import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import { VisualStudioCode } from "@/Components";

export default function Home() {
  return (
    <>
      <Head>
        <title>VS Code Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <VisualStudioCode />
      </main>
    </>
  );
}
